import assert from "node:assert/strict";
import { test } from "node:test";
import { spawn } from "node:child_process";
import { existsSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { chromium } from "playwright-core";
import { startDaemon, projectId, projectToken } from "@pointback/daemon";
import sharp from "sharp";

const edge = process.env.POINTBACK_BROWSER_PATH ?? "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge";
test("browser sends a review and redacts private screenshot pixels", { skip: !existsSync(edge) && "Set POINTBACK_BROWSER_PATH to a Chromium executable" }, async () => {
  const dataDir = mkdtempSync(join(tmpdir(), "pointback-browser-"));
  const root = join(process.cwd(), "examples/vanilla-vite");
  const daemon = startDaemon({ port: 0, dataDir });
  await new Promise<void>((resolve) => daemon.server.once("listening", resolve));
  const address = daemon.server.address(); if (!address || typeof address === "string") throw new Error("No daemon port");
  const base = `http://127.0.0.1:${address.port}`;
  const vite = spawn(join(process.cwd(), "node_modules/.bin/vite"), ["--host", "127.0.0.1", "--port", "5197", "--strictPort"], { cwd: root, env: { ...process.env, POINTBACK_DATA_DIR: dataDir, POINTBACK_PORT: String(address.port) }, stdio: "pipe" });
  let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
  try {
    let ready = false;
    for (let i = 0; i < 60; i++) {
      try { const result = await fetch("http://127.0.0.1:5197/"); if (result.ok) { ready = true; break; } } catch { /* Vite starting. */ }
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
    assert.ok(ready, "Vite did not start");
    browser = await chromium.launch({ executablePath: edge, headless: true });
    const page = await browser.newPage({ viewport: { width: 900, height: 700 } });
    await page.goto("http://127.0.0.1:5197/");
    await page.evaluate(() => scrollTo(0, 220));
    const overlay = page.locator("pointback-overlay");
    const launcher = overlay.locator("#launcher");
    assert.equal(await launcher.getAttribute("aria-expanded"), "false");
    await launcher.click();
    assert.equal(await launcher.getAttribute("aria-expanded"), "true");
    await overlay.locator("#element").hover();
    await overlay.locator("#tooltip").waitFor({ state: "visible" });
    assert.match(await overlay.locator("#tooltip").textContent() ?? "", /DOM element/);
    const helpButton = overlay.locator("#help-button");
    assert.match(await helpButton.getAttribute("title") ?? "", /How Pointback works/);
    await helpButton.click();
    assert.equal(await overlay.locator("#help").isVisible(), true);
    assert.match(await overlay.locator("#help").textContent() ?? "", /Queue comment/);
    await page.keyboard.press("Escape");
    assert.equal(await overlay.locator("#help").isVisible(), false);
    const launcherBox = await launcher.boundingBox();
    const panelBox = await overlay.locator("#panel").boundingBox();
    assert.ok(launcherBox && panelBox && launcherBox.x > 800 && panelBox.y + panelBox.height < launcherBox.y, "launcher sits below the menu in the same corner");
    assert.ok(panelBox.width <= 330, "popup stays compact");
    const panelHeader = overlay.locator(".panel-header");
    const headerBox = await panelHeader.boundingBox();
    assert.ok(headerBox);
    await page.mouse.move(headerBox.x + 65, headerBox.y + 16);
    await page.mouse.down();
    await page.mouse.move(headerBox.x - 130, headerBox.y - 80, { steps: 5 });
    await page.mouse.up();
    const moved = await overlay.locator("#panel").boundingBox();
    assert.ok(moved && moved.x < panelBox.x - 100 && moved.y < panelBox.y - 40, "header drag repositions popup");
    await page.reload();
    const restored = await overlay.locator("#panel").boundingBox();
    assert.ok(restored && Math.abs(restored.x - moved.x) < 3 && Math.abs(restored.y - moved.y) < 3, "popup position survives reload");
    await page.setViewportSize({ width: 450, height: 650 });
    await page.waitForFunction(() => {
      const panel = document.querySelector("pointback-overlay")?.shadowRoot?.querySelector("#panel")?.getBoundingClientRect();
      return panel && panel.x >= 8 && panel.right <= innerWidth - 8 && panel.y >= 8 && panel.bottom <= innerHeight - 8;
    }, undefined, { timeout: 3000 });
    const clamped = await overlay.locator("#panel").boundingBox();
    assert.ok(clamped && clamped.x >= 8 && clamped.x + clamped.width <= 442 && clamped.y >= 8 && clamped.y + clamped.height <= 642, `popup stays reachable on resize: ${JSON.stringify(clamped)}`);
    await page.setViewportSize({ width: 900, height: 700 });
    await panelHeader.focus();
    await page.keyboard.press("Home");
    const reset = await overlay.locator("#panel").boundingBox();
    assert.ok(reset && Math.abs(reset.x - panelBox.x) < 3, "Home restores default corner");
    await launcher.click();
    await page.keyboard.press("Control+Shift+r");
    assert.equal(await launcher.getAttribute("aria-expanded"), "true");
    await overlay.locator("#page").click();
    assert.equal(await overlay.locator("#page").getAttribute("aria-pressed"), "true");
    assert.match(await overlay.locator("#target-summary").textContent() ?? "", /Page/);
    await overlay.locator("textarea").fill("Increase contrast");
    await overlay.locator("#queue").click();
    await overlay.locator("#element").click();
    await page.locator("section[data-pointback-id='container']").click({ position: { x: 400, y: 105 } });
    await overlay.locator("textarea").fill("Review the container");
    await page.reload();
    assert.equal(await overlay.locator("#panel").isVisible(), true, "review menu reopens after reload");
    assert.equal(await overlay.locator("#send").textContent(), "Send queued (1)");
    assert.equal(await overlay.locator("textarea").inputValue(), "Review the container");
    await overlay.locator("#queue").click();
    await overlay.locator("#send").click();
    try { await overlay.locator("#status").getByText(/2 comment\(s\) sent/).waitFor({ timeout: 15000 }); }
    catch (error) { console.error("Pointback status:", await overlay.locator("#status").textContent()); throw error; }
    const project = projectId(root);
    const headers = { "x-pointback-project": project, "x-pointback-token": projectToken(project, dataDir) };
    const comments = await (await fetch(base + "/comments", { headers })).json() as { id: string; screenshotId?: string; target: { type: string; element?: { html: string; text: string } } }[];
    assert.equal(comments.length, 2);
    const element = comments.find((c) => c.target.type === "element")?.target.element;
    assert.ok(element);
    assert.doesNotMatch(element.html + element.text, /SECRET_PRIVATE_TEXT|SECRET_INPUT_VALUE|SECRET_HIDDEN_TEXT/);
    assert.ok(comments[0].screenshotId);
    const screenshot = await (await fetch(`${base}/screenshots/${comments[0].screenshotId}`, { headers })).json() as { image: string };
    const image = sharp(Buffer.from(screenshot.image, "base64"));
    const { data, info } = await image.raw().toBuffer({ resolveWithObject: true });
    assert.ok(info.width > 0 && info.height > 0 && data.length > 0);
    const pixel = (180 * info.width + 200) * info.channels;
    assert.deepEqual([...data.subarray(pixel, pixel + 3)], [0, 0, 0], "private region must be black");
    const background = (500 * info.width + 500) * info.channels;
    assert.deepEqual([...data.subarray(background, background + 3)], [255, 255, 255], "normal screenshot background must be visible");
    const elementMarker = overlay.locator(".marker[title='Review the container']");
    const anchored = await elementMarker.boundingBox();
    assert.ok(anchored);
    await page.evaluate(() => scrollTo(0, 180));
    await page.waitForFunction(() => {
      const element = document.querySelector('[data-pointback-id="container"]');
      const marker = document.querySelector("pointback-overlay")?.shadowRoot?.querySelector('.marker[title="Review the container"]');
      return element && marker && Math.abs(marker.getBoundingClientRect().top - element.getBoundingClientRect().top) < 2;
    });
    const scrolled = await elementMarker.boundingBox();
    assert.ok(scrolled && Math.abs(scrolled.y - (anchored.y - 180)) < 2, "element marker tracks page scrolling");
    await page.locator('[data-pointback-id="container"]').evaluate((element) => element.removeAttribute("data-pointback-id"));
    await page.evaluate(() => scrollTo(0, 260));
    await page.waitForFunction((expected) => {
      const marker = document.querySelector("pointback-overlay")?.shadowRoot?.querySelector('.marker[title="Review the container"]');
      return marker && Math.abs(marker.getBoundingClientRect().top - expected) < 2;
    }, anchored.y - 260);
    await page.locator("main > section").evaluate((element) => element.setAttribute("data-pointback-id", "container"));
    await page.evaluate(() => scrollTo(0, 420));
    const elementTask = overlay.locator(".comment-link").filter({ hasText: "Review the container" });
    await elementTask.click();
    await page.waitForFunction(() => scrollY < 80, undefined, { timeout: 3000 });
    assert.equal(await overlay.locator(".marker.selected[title='Review the container']").count(), 1, "task selection scrolls to its element marker");
    await elementTask.click();
    await page.evaluate(() => scrollTo(0, 0));
    await overlay.locator(".panel-body").evaluate((body) => { body.scrollTop = 0; });
    await overlay.locator(".marker[title='Review the container']").click();
    assert.equal(await overlay.locator(".comment-link").filter({ hasText: "Review the container" }).getAttribute("aria-current"), "true");
    await page.waitForFunction(() => {
      const shadow = document.querySelector("pointback-overlay")?.shadowRoot;
      const body = shadow?.querySelector(".panel-body")?.getBoundingClientRect();
      const row = [...(shadow?.querySelectorAll("#comments li") ?? [])].find((item) => item.querySelector(".comment-link")?.getAttribute("data-comment-id") === shadow?.querySelector(".marker.selected")?.getAttribute("data-comment-id"))?.getBoundingClientRect();
      return body && row && row.top >= body.top - 1 && row.bottom <= body.bottom + 1;
    }, undefined, { timeout: 3000 });
    await overlay.locator(".comment-link").filter({ hasText: "Increase contrast" }).click();
    assert.equal(await overlay.locator(".marker.selected[title='Increase contrast']").count(), 1, "page comments have selectable markers");
    const markerNumber = await overlay.locator(".marker.selected").textContent();
    assert.match(markerNumber ?? "", /^\d+$/, "markers display their comment number");
    assert.match(await overlay.locator(".comment-link").filter({ hasText: "Increase contrast" }).locator(".comment-text").textContent() ?? "", new RegExp(`^${markerNumber}\\. `), "task list shows the matching number");
    assert.equal(await overlay.locator("#comments li").filter({ hasText: "Increase contrast" }).locator(".target-type use").getAttribute("href"), "#pb-page");
    assert.equal(await overlay.locator("#comments li").filter({ hasText: "Review the container" }).locator(".target-type use").getAttribute("href"), "#pb-element");
    assert.equal(await overlay.locator(".marker.selected").getAttribute("aria-label"), `Show comment ${markerNumber}: Increase contrast`);
    const selected = overlay.locator(".comment-link").filter({ hasText: "Review the container" });
    await selected.click();
    assert.equal(await selected.getAttribute("aria-current"), "true");
    assert.equal(await overlay.locator(".marker.selected").count(), 1);
    assert.equal(await overlay.locator("#highlight").evaluate((node) => (node as HTMLElement).style.display), "block");
    await selected.click();
    assert.equal(await overlay.locator(".marker.selected").count(), 0, "second click toggles highlight off");
    await selected.click();
    assert.equal(await overlay.locator(".marker.selected").count(), 1);
    await page.waitForTimeout(3200);
    assert.equal(await overlay.locator(".marker.selected").count(), 0, "highlight automatically clears after three seconds");
    await page.waitForTimeout(300);
    assert.equal(await overlay.locator("#highlight").evaluate((node) => (node as HTMLElement).style.display), "none");
    const elementComment = comments.find((comment) => comment.target.type === "element")!;
    const resolved = await fetch(`${base}/comments/${elementComment.id}/resolve`, { method: "POST", headers });
    assert.equal(resolved.status, 200);
    await overlay.locator(".comment-link").filter({ hasText: "resolved: Review the container" }).waitFor();
    await overlay.locator("#hide-accepted").check();
    assert.equal(await overlay.locator(".comment-link").filter({ hasText: "resolved: Review the container" }).count(), 1, "resolved comments stay visible while filtering");
    assert.equal(await overlay.locator(".marker").count(), 2, "resolved marker stays visible while filtering");
    await overlay.locator("#comments li").filter({ hasText: "resolved: Review the container" }).getByRole("button", { name: "Accept" }).click();
    await overlay.locator(".comment-link").filter({ hasText: "Review the container" }).waitFor({ state: "detached" });
    assert.equal(await overlay.locator(".marker").count(), 1, "accepted marker is hidden");
    await page.reload();
    assert.equal(await overlay.locator("#hide-accepted").isChecked(), true);
    await overlay.locator("#hide-accepted").uncheck();
    await overlay.locator(".comment-link").filter({ hasText: "accepted: Review the container" }).waitFor();
    page.once("dialog", (dialog) => void dialog.accept());
    await overlay.locator("button[aria-label^='Delete completed comment: Review the container']").click();
    await overlay.locator(".comment-link").filter({ hasText: "Review the container" }).waitFor({ state: "detached" });
    assert.equal((await fetch(`${base}/screenshots/${comments[0].screenshotId}`, { headers })).status, 200);
    await overlay.locator("#page").click();
    await overlay.locator("textarea").fill("One-click feedback");
    await page.reload();
    assert.equal(await overlay.locator("#panel").isVisible(), true);
    assert.equal(await overlay.locator("textarea").inputValue(), "One-click feedback");
    await overlay.locator("textarea").press("Control+Enter");
    await overlay.locator("#status").getByText(/1 comment\(s\) sent/).waitFor({ timeout: 15000 });
    assert.equal(await overlay.locator("#send").textContent(), "Send queued (0)");
    const after = await (await fetch(base + "/comments", { headers })).json() as { message: string }[];
    assert.equal(after.length, 2);
    assert.ok(after.some((comment) => comment.message === "One-click feedback"));
    const sessions = await (await fetch(base + "/sessions", { headers })).json() as unknown[];
    assert.equal(sessions.length, 2);
    await page.evaluate(() => scrollTo(0, 120));
    await overlay.locator("#region").click();
    await page.mouse.move(250, 240);
    await page.mouse.down();
    await page.mouse.move(335, 315, { steps: 4 });
    await page.mouse.up();
    assert.match(await overlay.locator("#target-summary").textContent() ?? "", /Region/);
    await overlay.locator("textarea").fill("Region follows scrolling");
    await overlay.locator("#send-one").click();
    await overlay.locator(".marker[title='Region follows scrolling']").waitFor();
    assert.equal(await overlay.locator("#comments li").filter({ hasText: "Region follows scrolling" }).locator(".target-type use").getAttribute("href"), "#pb-region");
    const regionMarker = overlay.locator(".marker[title='Region follows scrolling']");
    const regionStart = await regionMarker.boundingBox();
    assert.ok(regionStart);
    const regionComments = await (await fetch(base + "/comments", { headers })).json() as { message: string; target: { scroll?: { y: number } } }[];
    assert.equal(regionComments.find((comment) => comment.message === "Region follows scrolling")?.target.scroll?.y, 120);
    await page.evaluate(() => scrollTo(0, 270));
    await page.waitForFunction((expected) => {
      const marker = document.querySelector("pointback-overlay")?.shadowRoot?.querySelector('.marker[title="Region follows scrolling"]');
      return marker && Math.abs(marker.getBoundingClientRect().top - expected) < 2;
    }, regionStart.y - 150);
    await page.evaluate(() => scrollTo(0, 400));
    await overlay.locator(".comment-link").filter({ hasText: "Region follows scrolling" }).click();
    await page.waitForFunction(() => scrollY < 200, undefined, { timeout: 3000 });
    const revealedRegion = await regionMarker.boundingBox();
    assert.ok(revealedRegion && revealedRegion.y >= 0 && revealedRegion.y < 700, "task selection reveals its region marker");
  } finally {
    await browser?.close(); vite.kill(); await daemon.close(); rmSync(dataDir, { recursive: true, force: true });
  }
});
